### PR TITLE
Fix #92

### LINKED ISSUE #92: Use Language selected for individual user instead the WordPress Site Language.
**Describe the bug**
My site is in Spanish for a shop in Spain, but I prefer to work in English. My admin account is set to English for that reason. Up to now all plug-ins settings I have seen show the admin user preferred language. Yours is the first exception to this tradition because it shows the site’s default language. In my opinion a plug-in should not oblige administrators to use a language that is not of their choice. 

**To Reproduce**
On Users > Add/Edit User page, I have set Spanish Language - https://prnt.sc/hH6eUw3ptI5d
The plugin language is in English as per My WordPress Site Language- https://prnt.sc/_XMROBW8HGOB

The plugin should show the strings of selected language for users. 

**Additional context**
https://wordpress.org/support/topic/admin-language-not-default-language/

### PR DESCRIPTION
**Pull request by nidhitatosaniya**
Added load_plugin_textdomain function

### CODE REVIEW

File: checkout-fees-for-woocommerce/checkout-fees-for-woocommerce.php [hunk 1]
```diff
@@ -91,11 +91,15 @@ public static function instance() {
 		public function __construct() {
 
 			// Set up localisation.
-			load_plugin_textdomain( 'checkout-fees-for-woocommerce', false, dirname( plugin_basename( __FILE__ ) ) . '/langs/' );
+			// load_plugin_textdomain( 'checkout-fees-for-woocommerce', false, dirname( plugin_basename( __FILE__ ) ) . '/langs/' );.
```
Comment (kartikparmar) [inline checkout-fees-for-woocommerce/checkout-fees-for-woocommerce.php:94]: Please remove the commented code

File: checkout-fees-for-woocommerce/checkout-fees-for-woocommerce.php [hunk 2]
```diff
@@ -91,11 +91,15 @@ public static function instance() {
...
 
 			// Include required files.
 			$this->includes();
 
+			if ( is_admin() ) {
```
Comment (kartikparmar) [inline checkout-fees-for-woocommerce/checkout-fees-for-woocommerce.php:99]: instead of this snippet, can we directly call the function? like `$this->load_plugin_textdomain()`

File: checkout-fees-for-woocommerce/checkout-fees-for-woocommerce.php [hunk 3]
```diff
@@ -149,6 +153,19 @@ public function includes() {
 			require_once 'includes/class-alg-wc-order-fees.php';
 		}
 
+		/**
+		 * Add trnslations as per user language.
```
Comment (kartikparmar) [inline checkout-fees-for-woocommerce/checkout-fees-for-woocommerce.php:157]: trnslations - translations

**Review by kartikparmar — APPROVED** [review]
