### PR TITLE
Fix #266 woo payment gatways name are not fetching

### LINKED ISSUE #266: The payment gateway names (labels) from WooPayments plugin are not displayed in the Payment Gateway Based Fees and Discounts tab.
### Prerequisites

- [x] I have carried out troubleshooting steps and I believe I have found a bug.
- [x] I have searched for similar bugs in both open and closed issues and cannot find a duplicate.

### Describe the bug

The payment gateway names (labels) from the WooPayments plugin are not displayed in the Payment Gateway Based Fees and Discounts tab. The shipping methods were displayed fine in the older version of WooPayments (8.5.0), the issue is with the latest version (8.8.0).

Tested with WooCommerce 9.6.0, Payment Gateway Based Fees and Discounts for WooCommerce 2.15.0, WooPayments 8.8.0

Image

Image

 

### Steps to reproduce

ef

### Expected behavior

The Payment Gateway names(labels) should come with the latest version of the WooPayment plugin.

### WordPress Environment

ef

### Isolating the problem

- [ ] I have deactivated other plugins and confirmed this bug occurs when only our plugin is active.
- [x] This bug happens with a default WordPress theme active, or [Storefront](https://woo.com/products/storefront/).
- [x] I can reproduce this bug consistently using the steps above.

### Additional field

Client: https://wordpress.org/support/topic/woopayment-cc-fees-settings-missing/

### PR DESCRIPTION
**Pull request by gaminikhil**
Fix #266 woo payment gatways title are not fetching

### CODE REVIEW

File: includes/settings/class-alg-wc-checkout-fees-settings-per-product.php [hunk 1]
```diff
@@ -353,7 +353,25 @@ public function add_meta_box() {
...
+					$sections[ sanitize_title( $key ) ] = str_replace( '_', ' ', $key );
+				}
+				if ( 'iyzico_pwi' === $key ) {
+					$sections[ sanitize_title( $key ) ] = $gateway->method_title;
+				}
+				if ( 'alma' === $key ) {
+					$sections[ sanitize_title( $key ) ] = $gateway->method_title;
+				}
+				if ( 'woocommerce_payments' === $key || 'woocommerce_payments_bancontact' === $key || 'woocommerce_payments_sepa_debit' === $key || 'woocommerce_payments_giropay' === $key || 'woocommerce_payments_sofort' === $key || 'woocommerce_payments_p24' === $key || 'woocommerce_payments_ideal' === $key || 'woocommerce_payments_au_becs_debit' === $key || 'woocommerce_payments_eps' === $key || 'woocommerce_payments_affirm' === $key || 'woocommerce_payments_afterpay_clearpay' === $key || 'woocommerce_payments_klarna' === $key ) {
+					$sections[ sanitize_title( $key ) ] = $gateway->get_title();
```
Comment (rashmimalpande) [inline includes/settings/class-alg-wc-checkout-fees-settings-per-product.php:372]: @gaminikhil Where is this $sections array used? And do we need to add a default value here?
