### PR TITLE
Fixed Maximum fee value option is not working as expected.

### LINKED ISSUE #235: Maximum fee value option is not working as expected
**Describe the bug**
The Maximum fee value option is not working as expected. The fee value that is added is exceeding the amount added in the Maximum fee value setting and the fee value is shown on the checkout page instead of the set Maximum fee value.

Tested with WooCommerce 8.9.1, PGBF 2.12.2 

**To Reproduce**
1. For a payment gateway, select 'Fee type' to 'Percent', 'Fee value' to '-5', and 'Maximum fee value' option to '-50': https://prnt.sc/6xd2ZydkV50F
2. When the product with 2000 price is added to the cart, the added discount from our plugin is '-100' on the checkout page instead of '-50'.
3. https://prnt.sc/NblY2MMuAxcV

I have checked with 'Fee type' to 'Fixed', but even that is not working.

**Expected behavior**
Maximum fee value option should work as needed.

**Additional context**
Ticket: https://support.tychesoftwares.com/conversation/2406?folder_id=13

### PR DESCRIPTION
**Pull request by mokshasharmila13**
Fix #235. Added a check when the maximum fees are set.

### CODE REVIEW

File: includes/class-alg-wc-checkout-fees.php [hunk 1]
```diff
@@ -549,7 +549,7 @@ public function calculate_the_fee( $args, $final_fee_to_add, $total_in_cart, $fe
 				$max_fee = 0;
 			}
 			// Max fee.
-			if ( 0 != $max_fee && $new_fee > $max_fee ) { //phpcs:ignore
+			if ( 0 != $max_fee && $new_fee < $max_fee ) { //phpcs:ignore
```
Comment (rashmimalpande) [inline includes/class-alg-wc-checkout-fees.php:552]: @mokshasharmila13 This is incorrect. This will not work when the fee value & max fee value is a positive value. You need to check for both positive & negative values

**Review by rashmimalpande — APPROVED** [review]
