### PR TITLE
Fix #199

### LINKED ISSUE #199: Payment gateway fees are not visible on the Checkout block page.
**Describe the bug**
Payment gateway fees are not visible on the Checkout block page. 

**To Reproduce**
1. Settings. https://app.screencast.com/iJZspuZqcwmIl
2. Add the product
3. Go to the Checkout block page the gateway fees do not appear on the checkout block page.

Checkout block page. : https://app.screencast.com/yMJy1glwYnxAN

**Expected behavior**
Payment gateway fees should be visible on the checkout block page.

### PR DESCRIPTION
**Pull request by nidhitatosaniya**
Fixed payment gateway fees are not visible on the Checkout block page. fix #199

### CODE REVIEW

File: includes/js/checkout-block-frontend.js [hunk 1]
```diff
@@ -0,0 +1,33 @@
+(()=>{
```
Comment (rashmimalpande) [inline includes/js/checkout-block-frontend.js:1]: @nidhitatosaniya You need to create a src folder with JS code and then create a build for it.

**Review by rashmimalpande — CHANGES_REQUESTED** [review]

File: checkout-block/class-blocks-integration.php [hunk 2]
```diff
@@ -69,7 +69,7 @@ public function register_block_frontend_scripts() {
 
 		wp_register_script(
 			'checkout-block-frontend',
-			trailingslashit( plugin_dir_url( __DIR__ ) ) . 'includes/js/checkout-block-frontend.js',
+			trailingslashit( plugin_dir_url( __DIR__ ) ) . 'src/frontend.js',
```
Comment (rashmimalpande) [inline checkout-block/class-blocks-integration.php]: Add the build folder checkout-block-frontend.js file

Comment (nidhitatosaniya) [reply checkout-block/class-blocks-integration.php]: See this final commit : https://github.com/TycheSoftwares/checkout-fees-for-woocommerce/pull/202/files#diff-39d28b094398981714ade49c6aea7b4e0d26e68045cd7db181aea61a1a4f86d2R72

**Review by rashmimalpande — APPROVED** [review]
