### PR TITLE
issue-55

### LINKED ISSUE #55: Compatibility with the Klarna payment gateway
**Describe the bug**
The issue is that the fees of the Klarna payment gateway are not added to the checkout page.

**To Reproduce**
1. Install the Klarna payment gateway: https://wordpress.org/plugins/klarna-payments-for-woocommerce/
2. Add fees to that payment gateway.
3. Add the product to the cart.
4. On the checkout page select Klarna payment gateway, you will not find the fees added which are set to the checkout page.

**Expected behavior**
The Klarna fees should be added to the checkout page. 

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/25399

### PR DESCRIPTION
**Pull request by Shasvat7**
Compatibility with Klarna payments gateway.
Fixes #55

### CODE REVIEW

File: checkout-fees-for-woocommerce/includes/class-alg-wc-checkout-fees.php [hunk 1]
```diff
@@ -296,7 +296,10 @@ public function add_gateways_fees( $the_cart ) {
 			if ( ! $current_gateway ) {
 				return;
 			}
-
+			$klarna_payment = 'klarna_payments';
+			if ( strpos( $current_gateway, $klarna_payment ) !== false ) {
+				$current_gateway = 'klarna_payments';
+			}
```
Comment (ashokrane) [inline checkout-fees-for-woocommerce/includes/class-alg-wc-checkout-fees.php:302]: Please add a comment here on why we needed to add this piece of code for Klarna gateway.

**Review by ashokrane — APPROVED** [review]
